### ISSUE TITLE
React Components need a different color

### ISSUE THREAD

**Issue by kyleshevlin** [chaance/night-lights#1]
I think the syntax elements, such as `<` and `>` are fine to be the dull gray, but it can be difficult to pick out the name of components in a sea of gray. Specifically `Spacer` and `CourseItem` in the photo below.

![Screen Shot 2021-09-01 at 2 11 47 PM](https://user-images.githubusercontent.com/4333144/131747728-560f332c-8067-4e40-a87d-1cf579b19375.JPG)

I think it would be useful to make them a different color so the component name stands out more.

**Comment by kyleshevlin** [comment]
@chaance and I chatted in a DM about this, and there's a bit of a "works on my machine" problem going on. It appears to work correctly for the language syntax of `TypeScript React` for me, but not for `TypeScript` or `Babel JavaScript`.

Setting `editor.semanticHighlighting.enabled` to a different setting results in no difference.

**Comment by chaance** [comment]
I added scopes for open and close tags specifically, which I believe should fix this for you. Still not entirely sure why I see JSX tags scoped differently, but let me know if this looks better for you in 0.2.2!
