### ISSUE TITLE
Search highlighting difficult to read

### ISSUE THREAD

**Issue by kyleshevlin** [chaance/night-lights#2]
In searching for a file to open, the marine text on blue highlight is very difficult to read.

![Screen Shot 2021-09-02 at 3 15 30 PM](https://user-images.githubusercontent.com/4333144/131923343-7096cb5d-d405-4f44-94f2-528fdca01a98.JPG)

**Comment by chaance** [comment]
Great catch, updated in 0.2.2. I think this looks a lot nicer to boot!

![screenshot showing search results with higher contrast](https://user-images.githubusercontent.com/3082153/132143009-62ebb562-52a3-4524-998f-43d3eb73d4d3.png)

**Comment by kyleshevlin** [comment]
Agreed, that's very nice looking. Well done.
